# Generated by Django 5.0.9 on 2025-08-04 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_picture', models.ImageField(blank=True, help_text='Profile picture of the customer', null=True, upload_to='customer_pictures/')),
                ('full_name', models.CharField(max_length=255)),
                ('parentage_husband', models.CharField(blank=True, help_text="Husband's name if applicable", max_length=255, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('address', models.TextField()),
                ('customer_type', models.CharField(choices=[('private', 'Private Regular'), ('govt', 'Government Servant'), ('wapda', 'Wapda Servant'), ('other', 'Other')], max_length=10)),
                ('occupation', models.CharField(blank=True, help_text='Occupation of the customer', max_length=100, null=True)),
                ('office_address', models.TextField(blank=True, help_text='Office address if applicable', null=True)),
                ('department', models.CharField(blank=True, help_text='Department if applicable', max_length=100, null=True)),
                ('office_phone', models.CharField(blank=True, help_text='Office phone number if applicable', max_length=20, null=True)),
                ('period_employed', models.CharField(blank=True, help_text='Period of employment if applicable', max_length=100, null=True)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False, help_text='Indicates if the customer profile is approved')),
                ('attached_file', models.FileField(blank=True, help_text='Attach any relevant file', null=True, upload_to='customer_files/')),
                ('attached_file_2', models.FileField(blank=True, help_text='Attach any relevant file', null=True, upload_to='customer_files/')),
                ('attached_file_3', models.FileField(blank=True, help_text='Attach any relevant file', null=True, upload_to='customer_files/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
