# Generated by Django 5.0.9 on 2025-08-04 18:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('father_husband_name', models.CharField(blank=True, help_text="Father's or Husband's name if applicable", max_length=255, null=True)),
                ('address', models.TextField(blank=True, help_text='Address of the staff member', null=True)),
                ('cnic', models.CharField(max_length=15, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('role', models.CharField(choices=[('shopkeeper', 'Shopkeeper'), ('sales_agent', 'Sales Agent'), ('manager', 'Manager')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('approved', models.BooleanField(default=False)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('staff_picture', models.ImageField(blank=True, null=True, upload_to='staff_pictures/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
