# Generated by Django 5.0.9 on 2025-08-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('shopkeeper', 'Shopkeeper'), ('sales_agent', 'Sales Agent'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('admin', 'Administrator'), ('other', 'Other')], max_length=20),
        ),
    ]
