# Generated by Django 5.0.9 on 2025-08-04 18:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('specs', models.TextField(blank=True)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('direct_cash_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('batch', models.CharField(blank=True, help_text='Batch number or identifier', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stock', models.IntegerField(default=0, help_text='Number of items in stock')),
                ('image', models.ImageField(blank=True, help_text='Product image', null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('other', 'Other')], max_length=50)),
                ('installment_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='InstallmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_increase', models.DecimalField(decimal_places=2, help_text='e.g. 10 for 10%', max_digits=5)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
                ('number_of_installments', models.IntegerField()),
                ('monthly_installment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.product')),
            ],
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantor_name_1', models.CharField(blank=True, help_text="Guarantor's name if applicable", max_length=255, null=True)),
                ('guarantor_cnic_1', models.CharField(blank=True, help_text="Guarantor's CNIC if applicable", max_length=15, null=True)),
                ('guarantor_contact_1', models.CharField(blank=True, help_text="Guarantor's contact number if applicable", max_length=20, null=True)),
                ('guarantor_name_2', models.CharField(blank=True, help_text="Second guarantor's name if applicable", max_length=255, null=True)),
                ('guarantor_cnic_2', models.CharField(blank=True, help_text="Second guarantor's CNIC if applicable", max_length=15, null=True)),
                ('guarantor_contact_2', models.CharField(blank=True, help_text="Second guarantor's contact number if applicable", max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='customer.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='sales.product')),
            ],
        ),
    ]
