# Generated by Django 5.0.9 on 2025-08-06 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True, help_text='Is the product available for sale?'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Additional product image', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Another product image', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Another product image', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='other_info',
            field=models.TextField(blank=True, help_text='Any other relevant information about the product', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, help_text='Number of items sold'),
        ),
    ]
