# Generated by Django 5.0.9 on 2025-08-06 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_image_product_image_1_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentsale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
