# Generated by Django 5.0 on 2025-08-07 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_installmentsale_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='product',
        ),
        migrations.AddField(
            model_name='payment',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.installmentsale'),
            preserve_default=False,
        ),
    ]
