# Generated by Django 5.0 on 2025-08-08 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_remove_payment_customer_remove_payment_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installmentsale',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partially Paid'), ('completed', 'Fully Paid')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('furniture', 'Furniture'), ('appliances', 'Appliances')], max_length=100),
        ),
    ]
