# Generated by Django 5.0 on 2025-08-09 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_remove_product_sold_alter_product_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0, help_text='Total units sold'),
        ),
    ]
